require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
   - 'bin/*'
   - 'db/**/*'
   - 'vendor/bundle/**/*'
   - 'node_modules/**/*'
   - 'spec/**/*'
   - 'config/environments/*'

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'db/migrate/*'

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/ParameterLists:
  Max: 6

Metrics/BlockNesting:
  Max: 4

Naming/MemoizedInstanceVariableName:
  Enabled: false

Security/Open:
  Enabled: false

Lint/UriEscapeUnescape:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'app/admin/**/*'
    - 'config/**/*'
    - 'db/migrate/*'
    - 'spec/**/*'
    - 'lib/tasks/*'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/migrate/*'

Rails:
  Enabled: true

Naming/RescuedExceptionsVariableName:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/NumericLiterals:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

# Style/StringLiterals:
#   EnforcedStyle: double_quotes

Naming/VariableNumber:
  EnforcedStyle: snake_case

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Style/WordArray:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'lib/tasks/*'
    - 'config/initializers/*'

Style/Lambda:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/EnumHash:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/HelperInstanceVariable:
  Exclude:
    - 'app/helpers/application_helper.rb'

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false
